-- SQL setup for Supabase tables used by the Admin Panel
-- Run these statements in the Supabase SQL editor (or via psql)

-- 1) assets table: stores key -> public URL mappings for images
CREATE TABLE IF NOT EXISTS public.assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2) bookings table: stores bookings and amount which we use for revenue
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT,
  phone TEXT,
  email TEXT,
  amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  currency TEXT DEFAULT 'USD',
  status TEXT DEFAULT 'pending', -- e.g. pending, paid, cancelled
  booked_at TIMESTAMPTZ DEFAULT now(),
  details JSONB
);

-- Ensure the phone column exists for existing installations
ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS phone TEXT;

-- Optional index to query paid bookings quickly
CREATE INDEX IF NOT EXISTS idx_bookings_status ON public.bookings (status);

-- 3) Development policies for the public booking form and the current
-- password-gated admin UI. Run these in the Supabase SQL Editor after the
-- tables above. The admin page currently uses the anonymous key, so it needs
-- these policies to read/write assets and update booking payment statuses.
-- Before a production launch, replace the admin policies with Supabase Auth.
ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can create booking requests" ON public.bookings;
CREATE POLICY "Public can create booking requests"
  ON public.bookings FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Admin UI can read bookings" ON public.bookings;
CREATE POLICY "Admin UI can read bookings"
  ON public.bookings FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Admin UI can update bookings" ON public.bookings;
CREATE POLICY "Admin UI can update bookings"
  ON public.bookings FOR UPDATE TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admin UI can read assets" ON public.assets;
CREATE POLICY "Admin UI can read assets"
  ON public.assets FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Admin UI can write assets" ON public.assets;
CREATE POLICY "Admin UI can write assets"
  ON public.assets FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Admin UI can update assets" ON public.assets;
CREATE POLICY "Admin UI can update assets"
  ON public.assets FOR UPDATE TO anon USING (true) WITH CHECK (true);

-- 4) Create a PUBLIC Storage bucket named exactly `Public` (capital P) in
-- Storage > New bucket, then run these Storage policies for that bucket.
DROP POLICY IF EXISTS "Admin UI can upload portfolio images" ON storage.objects;
CREATE POLICY "Admin UI can upload portfolio images"
  ON storage.objects FOR INSERT TO anon WITH CHECK (bucket_id = 'Public');

DROP POLICY IF EXISTS "Admin UI can replace portfolio images" ON storage.objects;
CREATE POLICY "Admin UI can replace portfolio images"
  ON storage.objects FOR UPDATE TO anon USING (bucket_id = 'Public') WITH CHECK (bucket_id = 'Public');

-- Helpful sample rows (remove in production)
-- INSERT INTO public.assets (key, url) VALUES ('gallery_item1', 'https://example.com/foo.jpg') ON CONFLICT (key) DO NOTHING;
-- INSERT INTO public.bookings (customer_name, email, amount, currency, status) VALUES ('Alice', 'alice@example.com', 120.00, 'USD', 'paid');

-- Notes:
-- - The admin UI expects a public Supabase Storage bucket (named `public`) for image uploads and the `assets` table for mapping keys to public URLs.
-- - Make sure your anon key allows SELECT/INSERT/UPDATE on the `assets` table if you are not using RLS. For safety, consider enabling Row Level Security and using Supabase Auth for admin operations.
