-- SQL setup for Supabase tables used by the Admin Panel
-- Run these statements in the Supabase SQL editor (or via psql)

-- 1) assets table: stores key -> public URL mappings for images
CREATE TABLE IF NOT EXISTS public.assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2) bookings table: stores bookings and amount which we use for revenue
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT,
  phone TEXT,
  email TEXT,
  amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  currency TEXT DEFAULT 'NGN',
  status TEXT DEFAULT 'pending', -- e.g. pending, paid, cancelled
  booked_at TIMESTAMPTZ DEFAULT now(),
  details JSONB
);

-- Ensure the phone column exists for existing installations
ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS phone TEXT;

-- Use Nigerian naira for all new bookings and existing dashboard labels.
ALTER TABLE public.bookings
  ALTER COLUMN currency SET DEFAULT 'NGN';
UPDATE public.bookings SET currency = 'NGN' WHERE currency IS NULL OR currency = 'USD';

-- Optional index to query paid bookings quickly
CREATE INDEX IF NOT EXISTS idx_bookings_status ON public.bookings (status);

-- 2a) Services shown on the public website and in the booking form.
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  price TEXT,
  image_url TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Seed the three services already visible on the website. They can then be
-- edited or deleted from Admin > Services.
INSERT INTO public.services (title, description, price, image_url, sort_order)
VALUES
  ('Bridal Glam', 'Flawless, long-lasting makeup tailored for your special day. Includes a full consultation, skin prep, and premium lashes.', 'From ₦50,000', 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=800&auto=format&fit=crop', 1),
  ('Soft Glam', 'A beautifully blended, radiant look perfect for events, photoshoots, or date nights. Enhances your features without feeling heavy.', 'From ₦30,000', 'https://images.unsplash.com/photo-1512496015851-a1cbfc38d011?q=80&w=800&auto=format&fit=crop', 2),
  ('Editorial & Creative', 'Bold, artistic makeup for fashion shoots and creative projects. Designed to look striking on camera under professional lighting.', 'Custom', 'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?q=80&w=800&auto=format&fit=crop', 3)
ON CONFLICT (title) DO NOTHING;

-- 2b) Dates Vicky is unavailable for appointments.
CREATE TABLE IF NOT EXISTS public.unavailable_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unavailable_date DATE NOT NULL UNIQUE,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2c) Studio-wide daily booking capacity. The single row is intentionally
-- shared: change its number in Admin > Unavailable dates.
CREATE TABLE IF NOT EXISTS public.business_settings (
  id BOOLEAN PRIMARY KEY DEFAULT true CHECK (id = true),
  daily_booking_limit INTEGER NOT NULL DEFAULT 3 CHECK (daily_booking_limit > 0),
  updated_at TIMESTAMPTZ DEFAULT now()
);
INSERT INTO public.business_settings (id, daily_booking_limit)
VALUES (true, 3)
ON CONFLICT (id) DO NOTHING;

-- 3) Development policies for the public booking form and the current
-- password-gated admin UI. Run these in the Supabase SQL Editor after the
-- tables above. The admin page currently uses the anonymous key, so it needs
-- these policies to read/write assets and update booking payment statuses.
-- Before a production launch, replace the admin policies with Supabase Auth.
ALTER TABLE public.assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unavailable_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_settings ENABLE ROW LEVEL SECURITY;

-- Bookings are now inserted only through create_booking_request below so the
-- date limit cannot be bypassed from a browser request.
DROP POLICY IF EXISTS "Public can create booking requests" ON public.bookings;

DROP POLICY IF EXISTS "Admin UI can read bookings" ON public.bookings;
CREATE POLICY "Admin UI can read bookings"
  ON public.bookings FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Admin UI can update bookings" ON public.bookings;
CREATE POLICY "Admin UI can update bookings"
  ON public.bookings FOR UPDATE TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public can read services" ON public.services;
CREATE POLICY "Public can read services"
  ON public.services FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Admin UI can add services" ON public.services;
CREATE POLICY "Admin UI can add services"
  ON public.services FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Admin UI can update services" ON public.services;
CREATE POLICY "Admin UI can update services"
  ON public.services FOR UPDATE TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Admin UI can delete services" ON public.services;
CREATE POLICY "Admin UI can delete services"
  ON public.services FOR DELETE TO anon USING (true);

DROP POLICY IF EXISTS "Public can read unavailable dates" ON public.unavailable_dates;
CREATE POLICY "Public can read unavailable dates"
  ON public.unavailable_dates FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Admin UI can block unavailable dates" ON public.unavailable_dates;
CREATE POLICY "Admin UI can block unavailable dates"
  ON public.unavailable_dates FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Admin UI can reopen unavailable dates" ON public.unavailable_dates;
CREATE POLICY "Admin UI can reopen unavailable dates"
  ON public.unavailable_dates FOR DELETE TO anon USING (true);

DROP POLICY IF EXISTS "Public can read business settings" ON public.business_settings;
CREATE POLICY "Public can read business settings"
  ON public.business_settings FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Admin UI can update business settings" ON public.business_settings;
CREATE POLICY "Admin UI can update business settings"
  ON public.business_settings FOR UPDATE TO anon USING (true) WITH CHECK (true);

-- Atomically checks both blocked dates and capacity, then creates a request.
-- This avoids two people taking the last slot at the same time.
CREATE OR REPLACE FUNCTION public.create_booking_request(
  p_customer_name TEXT,
  p_phone TEXT,
  p_email TEXT,
  p_service TEXT,
  p_preferred_date DATE,
  p_notes TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  booking_limit INTEGER;
  existing_bookings INTEGER;
BEGIN
  IF p_preferred_date < CURRENT_DATE THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Please choose a future date.');
  END IF;
  IF EXISTS (SELECT 1 FROM public.unavailable_dates WHERE unavailable_date = p_preferred_date) THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Sorry, this date is unavailable. Please choose another date.');
  END IF;
  SELECT daily_booking_limit INTO booking_limit FROM public.business_settings WHERE id = true FOR UPDATE;
  SELECT COUNT(*) INTO existing_bookings FROM public.bookings
    WHERE details->>'preferred_date' = p_preferred_date::TEXT
      AND COALESCE(LOWER(status), 'pending') <> 'cancelled';
  IF existing_bookings >= booking_limit THEN
    RETURN jsonb_build_object('ok', false, 'message', 'Sorry, this day is fully booked. Please choose another date.');
  END IF;
  INSERT INTO public.bookings (customer_name, phone, email, status, details)
    VALUES (p_customer_name, p_phone, p_email, 'pending', jsonb_build_object('service', p_service, 'preferred_date', p_preferred_date::TEXT, 'notes', p_notes));
  RETURN jsonb_build_object('ok', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_booking_request(TEXT, TEXT, TEXT, TEXT, DATE, TEXT) TO anon;

DROP POLICY IF EXISTS "Admin UI can read assets" ON public.assets;
CREATE POLICY "Admin UI can read assets"
  ON public.assets FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Admin UI can write assets" ON public.assets;
CREATE POLICY "Admin UI can write assets"
  ON public.assets FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Admin UI can update assets" ON public.assets;
CREATE POLICY "Admin UI can update assets"
  ON public.assets FOR UPDATE TO anon USING (true) WITH CHECK (true);

-- 4) Create a PUBLIC Storage bucket named exactly `Public` (capital P) in
-- Storage > New bucket, then run these Storage policies for that bucket.
DROP POLICY IF EXISTS "Admin UI can upload portfolio images" ON storage.objects;
CREATE POLICY "Admin UI can upload portfolio images"
  ON storage.objects FOR INSERT TO anon WITH CHECK (bucket_id = 'Public');

DROP POLICY IF EXISTS "Admin UI can replace portfolio images" ON storage.objects;
CREATE POLICY "Admin UI can replace portfolio images"
  ON storage.objects FOR UPDATE TO anon USING (bucket_id = 'Public') WITH CHECK (bucket_id = 'Public');

-- Helpful sample rows (remove in production)
-- INSERT INTO public.assets (key, url) VALUES ('gallery_item1', 'https://example.com/foo.jpg') ON CONFLICT (key) DO NOTHING;
-- INSERT INTO public.bookings (customer_name, email, amount, currency, status) VALUES ('Alice', 'alice@example.com', 50000.00, 'NGN', 'paid');

-- Notes:
-- - The admin UI expects a public Supabase Storage bucket (named `public`) for image uploads and the `assets` table for mapping keys to public URLs.
-- - Make sure your anon key allows SELECT/INSERT/UPDATE on the `assets` table if you are not using RLS. For safety, consider enabling Row Level Security and using Supabase Auth for admin operations.
